In [12]:
import os
os.environ["MLFLOW_TRACKING_URI"] = "sqlite:///mlflow.db"  # must be set before any LazyClassifier() is created

import pandas as pd
import mlflow
from sklearn.model_selection import GroupShuffleSplit
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTENC
from lazypredict.Supervised import LazyClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [13]:
TARGET_ROWS = 30000
TOLERANCE = 0.15  # skip any single repo that alone would push total too far past target

df = pd.read_csv("../data/processed/pr_snapshots_clean_v2.csv")

repo_sizes = df.groupby("repo_key").size().sample(frac=1, random_state=42)
keep_repos, total = [], 0
for repo, size in repo_sizes.items():
    if total >= TARGET_ROWS:
        break
    if total + size > TARGET_ROWS * (1 + TOLERANCE):
        continue
    keep_repos.append(repo)
    total += size

df = df[df.repo_key.isin(keep_repos)].copy()
print(f"{len(keep_repos)} repos, {len(df)} rows")

y = df.pop("merged_before_next")
X = df.select_dtypes(include="number").drop(columns=["pr_id", "number", "timeline_data_available"], errors="ignore")
print(f"shape: {X.shape}, target distribution: {y.value_counts().to_dict()}")

5 repos, 30867 rows
shape: (30867, 24), target distribution: {0: 19349, 1: 11518}

In [14]:
# group split: whole repos held out, never split across train/test
splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(splitter.split(X, y, groups=df["repo_key"]))
X_train, X_test = X.iloc[train_idx].copy(), X.iloc[test_idx].copy()
y_train, y_test = y.iloc[train_idx].copy(), y.iloc[test_idx].copy()
print(f"train repos: {df.repo_key.iloc[train_idx].nunique()}, test repos: {df.repo_key.iloc[test_idx].nunique()}")

train repos: 4, test repos: 1

In [21]:
# run 1: SMOTE, all ~30 models. SMOTE needs no NaN and can't see test data -- impute + resample train only.
# SMOTENC (not plain SMOTE) so binary/checkpoint-style columns don't get interpolated into fractions.
imputer = SimpleImputer(strategy="median")
X_train_imp = pd.DataFrame(imputer.fit_transform(X_train), columns=X_train.columns, index=X_train.index)

categorical_cols = ["checkpoint_day", "created_dow", "created_hour", "reviewer_assigned",
                    "has_response_yet", "is_first_time_contributor"]
cat_idx = [X_train_imp.columns.get_loc(c) for c in categorical_cols if c in X_train_imp.columns]

smote = SMOTENC(categorical_features=cat_idx, random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_imp, y_train)
print(f"before: {y_train.value_counts().to_dict()}, after SMOTE: {y_train_res.value_counts().to_dict()}")

mlflow.set_experiment("pr_bottleneck_smote")

# --- FIX STARTS HERE ---
# 1. End any currently active/dangling run
if mlflow.active_run():
    mlflow.end_run()

# 2. Temporarily disable autologging to prevent LazyClassifier loop crashes
mlflow.autolog(disable=True) 
# -----------------------

clf_smote = LazyClassifier(verbose=0, ignore_warnings=False, predictions=False)
models_smote, _ = clf_smote.fit(X_train_res, X_test, y_train_res, y_test)

# (Optional) Re-enable autologging for the rest of your notebook
mlflow.autolog(disable=False)

models_smote

2026/07/17 14:23:43 WARNING mlflow.sklearn: Failed to infer model signature: the trained model does not have a `predict` or `transform` function, which is required in order to infer the signature
2026/07/17 14:23:43 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/07/17 14:23:43 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!
2026/07/17 14:23:49 WARNING mlflow.sklearn: Training metrics will not be recorded because training labels were not specified. To automatically record training metrics, provide training labels as inputs to the model training function.
2026/07/17 14:23:54 INFO mlflow.tracking.fluent: Autologging successfully enabled for lightgbm.
2026/07/17 14:23:54 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.

before: {0: 16193, 1: 9805}, after SMOTE: {0: 16193, 1: 16193}

2026/07/17 14:23:54 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
2026/07/17 14:23:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:24:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model AdaBoostClassifier to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
2026/07/17 14:24:14 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:24:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model BaggingClassifier to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
2026/07/17 14:24:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:24:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model BernoulliNB to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
2026/07/17 14:24:44 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:24:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:24:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model CalibratedClassifierCV to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
CategoricalNB model failed to execute: Negative values in data passed to CategoricalNB (input X).
2026/07/17 14:25:00 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:25:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:25:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:25:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model DecisionTreeClassifier to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
2026/07/17 14:25:13 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:25:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:25:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2026/07/17 14:25:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Failed to log model DummyClassifier to MLflow: The sklearn model could not be serialized in the skops serialization format. skops does not support custom functions or classes that are not defined at the top level. To work around this limitation, you can set the serialization_format 'cloudpickle', while exercising caution due to the possible arbitrary code during model deserialization using CloudPickle.
2026/07/17 14:25:27 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:3424: FutureWarning: `y_pred` was renamed to `y_proba` in version 1.9 and will be removed in 1.11. Use `y_proba` instead.
  warnings.warn(
2026/07/17 14:25:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "C:\Users\VEDANG BARMAN\Desktop\Git_Pr_prediction\venv\Lib\site-packages\mlflow\types\utils.py:440: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
XGBClassifier,0.628671,0.648167,0.688993,0.636776,0.681084,0.628671,10.113117
LGBMClassifier,0.637708,0.640191,0.687225,0.645522,0.669834,0.637708,9.632716
AdaBoostClassifier,0.619018,0.622838,0.660175,0.627421,0.654648,0.619018,12.161321
RandomForestClassifier,0.578558,0.617785,0.658864,0.583823,0.662050,0.578558,19.522803
Perceptron,0.544260,0.614416,0.672216,0.535494,0.683853,0.544260,7.772358
PassiveAggressiveClassifier,0.512426,0.603872,0.622712,0.485050,0.703528,0.512426,21.882203
LogisticRegression,0.581844,0.602570,0.622380,0.590474,0.640272,0.581844,9.478290
NuSVC,0.581639,0.594938,0.610939,0.590868,0.631473,0.581639,445.597949
LinearSVC,0.580407,0.594255,0.617691,0.589626,0.630973,0.580407,9.172485
BaggingClassifier,0.616759,0.593870,0.637540,0.621232,0.627918,0.616759,13.988715
SVC,0.594167,0.593525,0.635598,0.602996,0.628016,0.594167,352.886334
RidgeClassifier,0.571575,0.590378,0.610050,0.580518,0.628603,0.571575,9.040993
RidgeClassifierCV,0.571370,0.590353,0.609826,0.580296,0.628625,0.571370,7.864470
LinearDiscriminantAnalysis,0.571370,0.590086,0.610096,0.580324,0.628314,0.571370,12.332089
ExtraTreesClassifier,0.511604,0.578282,0.625005,0.502415,0.639418,0.511604,22.611379
BernoulliNB,0.542411,0.577357,0.583892,0.548347,0.621242,0.542411,8.919047
NearestCentroid,0.553707,0.569255,0.584206,0.563180,0.608548,0.553707,8.161947
CalibratedClassifierCV,0.577326,0.568523,0.616334,0.585886,0.605181,0.577326,15.102473
DecisionTreeClassifier,0.564592,0.564973,0.564973,0.574280,0.602627,0.564592,11.198909
KNeighborsClassifier,0.568289,0.561686,0.585566,0.577382,0.599195,0.568289,21.499928
LabelSpreading,0.544054,0.546461,NaN,0.554294,0.586160,0.544054,741.972488
LabelPropagation,0.543849,0.546036,NaN,0.554091,0.585759,0.543849,664.123021
SGDClassifier,0.582871,0.542106,0.605363,0.582619,0.582370,0.582871,8.022626
GaussianNB,0.395564,0.529341,0.601310,0.280387,0.700285,0.395564,10.742439
ExtraTreeClassifier,0.503800,0.522215,0.522215,0.513245,0.565109,0.503800,10.312625
DummyClassifier,0.648182,0.500000,0.500000,0.509823,0.420140,0.648182,11.125263

In [16]:
mlflow.end_run()

In [23]:
# Sum up the total time taken by all models in seconds
total_seconds = models_smote['Time Taken'].sum()

# Convert it to minutes and seconds for better readability
minutes = int(total_seconds // 60)
seconds = int(total_seconds % 60)

print(f"Total LazyPredict execution time: {total_seconds:.2f} seconds")
print(f"Formatted time: {minutes} minutes and {seconds} seconds")

Total LazyPredict execution time: 2475.24 seconds
Formatted time: 41 minutes and 15 seconds

In [24]:
models_smote

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
XGBClassifier,0.628671,0.648167,0.688993,0.636776,0.681084,0.628671,10.113117
LGBMClassifier,0.637708,0.640191,0.687225,0.645522,0.669834,0.637708,9.632716
AdaBoostClassifier,0.619018,0.622838,0.660175,0.627421,0.654648,0.619018,12.161321
RandomForestClassifier,0.578558,0.617785,0.658864,0.583823,0.662050,0.578558,19.522803
Perceptron,0.544260,0.614416,0.672216,0.535494,0.683853,0.544260,7.772358
PassiveAggressiveClassifier,0.512426,0.603872,0.622712,0.485050,0.703528,0.512426,21.882203
LogisticRegression,0.581844,0.602570,0.622380,0.590474,0.640272,0.581844,9.478290
NuSVC,0.581639,0.594938,0.610939,0.590868,0.631473,0.581639,445.597949
LinearSVC,0.580407,0.594255,0.617691,0.589626,0.630973,0.580407,9.172485
BaggingClassifier,0.616759,0.593870,0.637540,0.621232,0.627918,0.616759,13.988715
SVC,0.594167,0.593525,0.635598,0.602996,0.628016,0.594167,352.886334
RidgeClassifier,0.571575,0.590378,0.610050,0.580518,0.628603,0.571575,9.040993
RidgeClassifierCV,0.571370,0.590353,0.609826,0.580296,0.628625,0.571370,7.864470
LinearDiscriminantAnalysis,0.571370,0.590086,0.610096,0.580324,0.628314,0.571370,12.332089
ExtraTreesClassifier,0.511604,0.578282,0.625005,0.502415,0.639418,0.511604,22.611379
BernoulliNB,0.542411,0.577357,0.583892,0.548347,0.621242,0.542411,8.919047
NearestCentroid,0.553707,0.569255,0.584206,0.563180,0.608548,0.553707,8.161947
CalibratedClassifierCV,0.577326,0.568523,0.616334,0.585886,0.605181,0.577326,15.102473
DecisionTreeClassifier,0.564592,0.564973,0.564973,0.574280,0.602627,0.564592,11.198909
KNeighborsClassifier,0.568289,0.561686,0.585566,0.577382,0.599195,0.568289,21.499928
LabelSpreading,0.544054,0.546461,NaN,0.554294,0.586160,0.544054,741.972488
LabelPropagation,0.543849,0.546036,NaN,0.554091,0.585759,0.543849,664.123021
SGDClassifier,0.582871,0.542106,0.605363,0.582619,0.582370,0.582871,8.022626
GaussianNB,0.395564,0.529341,0.601310,0.280387,0.700285,0.395564,10.742439
ExtraTreeClassifier,0.503800,0.522215,0.522215,0.513245,0.565109,0.503800,10.312625
DummyClassifier,0.648182,0.500000,0.500000,0.509823,0.420140,0.648182,11.125263